// 圆角分
const modes = {1: '元', 2: '角', 3: '分', 4: '厘'};
const modes2 = {1: '元', 2: '角', 3: '分'};
const digitalPos = {'w': '万位', 'q': '千位', 'b': '百位', 's': '十位', 'g': '个位'};
export default {
    dfmmc: {
        'dyprize': true,
        'name': '极速秒秒乐',
        'pattern': 'digital',
        'type': 1,
        'len': 5,
        'default_methodid': 'HZX3',
        'hasrx': true,
        'positions': digitalPos,
        'trend': '/trend?lotteryid=dfmmc&count=30',
        'desc': '随时投随时开',
        'fastopen': true,
        'selfopen': true,
        'modes': modes2,
        'tag':'N'
    },
    dfffc: {
        'dyprize': true,
        'name': '夺金60秒',
        'pattern': 'digital',
        'type': 1,
        'len': 5,
        'default_methodid': 'HZX3',
        'hasrx': true,
        'positions': digitalPos,
        'trend': '/trend?lotteryid=dfffc&count=30',
        'desc': '04:00-02:00每分钟一期，全天1320期',
        'selfopen': true,
        'modes': modes2,
        'tag':'N'
    },
    dfssc: {
        'dyprize': true,
        'name': '好运三分彩',
        'pattern': 'digital',
        'type': 1,
        'len': 5,
        'default_methodid': 'HZX3',
        'hasrx': true,
        'positions': digitalPos,
        'trend': '/trend?lotteryid=dfssc&count=30',
        'desc': '04:00-02:00每3分钟一期，全天440期',
        'selfopen': true,
        'modes': modes2,
        'tag':'N'
    },
    df30: {
        "dyprize": true,
        "name": "好运30秒",
        "pattern": "digital",
        "type": 1,
        "len": 5,
        "default_methodid": "HZX3",
        'hasrx': true,
        'positions': digitalPos,
        'trend': '/trend?lotteryid=df30&count=30',
        'desc': '04:00-02:00每30秒一期，全天2640期',
        'selfopen': true,
        'modes': modes2,
        'tag':'N'
    },
    df3d: {
        "dyprize": true,
        "name": "好运3D",
        "pattern": "digital3",
        "type": 3,
        "len": 3,
        "default_methodid": "ZX3",
        'trend': '/trend?lotteryid=df3d&count=30',
        'desc': '04:00-02:00每分钟一期，全天1320期',
        'selfopen': true,
        'modes': modes2,
        'tag':'N'
    },
    // "df28": {
    //     "dyprize": true,
    //     "name": "丰狂28",
    //     "pattern": "df28",
    //     "type": 3,
    //     "len": 3,
    //     "default_methodid":"ZXHZ",
    //     'trend':'/trend?lotteryid=df28&count=30',
    //     'desc':'04:00-02:00每3分钟一期，全天440期',
    //     'selfopen':true,
    //     'custom':true,
    //     'pool':true,
    //     'modes':modes2
    // },
    cqssc: {
        'dyprize': true,
        'name': '重庆时时彩',
        'pattern': 'digital',
        'type': 1,
        'len': 5,
        'default_methodid': 'HZX3',
        'hasrx': true,
        'positions': digitalPos,
        'trend': '/trend?lotteryid=cqssc&count=30',
        'desc': '10:00-02:00每(10或5分钟)一期，全天120期',
        'tag':'H',
        modes
    },
    xjssc: {
        'dyprize': true,
        'name': '新疆时时彩',
        'pattern': 'digital',
        'type': 1,
        'len': 5,
        'default_methodid': 'HZX3',
        'hasrx': true,
        'positions': digitalPos,
        'trend': '/trend?lotteryid=xjssc&count=30',
        'desc': '10:10-02:00每10分钟一期，全天96期',
        'tag':'H',
        modes
    },
    // hljssc: {
    //   'dyprize': true,
    //   'name': '黑龙江时时彩',
    //   'pattern': 'digital',
    //   'type': 1,
    //   'len': 5,
    //   'default_methodid': 'HZX3',
    //   'hasrx': true,
    //   'positions': digitalPos,
    //   'trend': '/trend?lotteryid=hljssc&count=30',
    //   'desc': '05:00-22:40每10分钟一期，全天84期',
    //   modes
    // },
    tjssc: {
        'dyprize': true,
        'name': '天津时时彩',
        'pattern': 'digital',
        'type': 1,
        'len': 5,
        'default_methodid': 'HZX3',
        'hasrx': true,
        'positions': digitalPos,
        'trend': '/trend?lotteryid=tjssc&count=30',
        'desc': '05:00-23:00每10分钟一期，全天84期',
        modes
    },
    // jxssc: {
    //   'dyprize': true,
    //   'name': '江西时时彩',
    //   'pattern': 'digital',
    //   'type': 1,
    //   'len': 5,
    //   'default_methodid': 'HZX3',
    //   'hasrx': true,
    //   'positions': digitalPos,
    //   'trend': '/trend?lotteryid=jxssc&count=30',
    //   'desc': '05:00-23:00每10分钟一期，全天84期',
    //   modes
    // },
    txffc: {
      'dyprize': true,
      'name': '腾讯分分彩',
      'pattern': 'digital',
      'type': 1,
      'len': 5,
      'default_methodid': 'HZX3',
      'hasrx': true,
      'positions': digitalPos,
      'trend': '/trend?lotteryid=txffc&count=30',
      'desc': '05:00-23:00每分钟一期，全天2000期',
      modes
    },
    df115: {
        'dyprize': true,
        'name': '好运11选5',
        'pattern': 'lotto',
        'type': 2,
        'len': 5,
        'default_methodid': 'LTZX3',
        'trend': '/trend?lotteryid=df115&count=30',
        'desc': '05:00-21:55每10分钟一期，全天78期',
        modes
    },
    sd115: {
        'dyprize': true,
        'name': '山东11选5',
        'pattern': 'lotto',
        'type': 2,
        'len': 5,
        'default_methodid': 'LTZX3',
        'trend': '/trend?lotteryid=sd115&count=30',
        'desc': '05:00-21:55每10分钟一期，全天78期',
        modes
    },
    jx115: {
        'dyprize': true,
        'name': '江西多乐彩',
        'pattern': 'lotto',
        'type': 2,
        'len': 5,
        'default_methodid': 'LTZX3',
        'trend': '/trend?lotteryid=jx115&count=30',
        'desc': '05:00-22:00每10分钟一期，全天78期',
        modes
    },
    gd115: {
        'dyprize': true,
        'name': '广东11选5',
        'pattern': 'lotto',
        'type': 2,
        'len': 5,
        'default_methodid': 'LTZX3',
        'trend': '/trend?lotteryid=gd115&count=30',
        'desc': '05:00-23:00每10分钟一期，全天84期',
        modes
    },
    'sh115': {
       'dyprize': true,
       'name': '上海11选5',
       'pattern': 'lotto',
       'type': 2,
       'len': 5,
       'point' : 7.0,
       'default_methodid':'LTZX3',
       'trend':'/trend?lotteryid=sh115&count=30',
       'desc':'05:00-23:00(10钟)，全天84期',
      modes
    },
    fc3d: {
        'dyprize': true,
        'name': '福彩3D',
        'pattern': 'digital3',
        'type': 3,
        'len': 3,
        'default_methodid': 'ZX3',
        'trend': '/trend?lotteryid=fc3d&count=30',
        'desc': '当天20:30-第二天20:00，每天一期',
        modes
    },
    shssl: {
        'dyprize': true,
        'name': '上海时时乐',
        'pattern': 'digital3',
        'type': 3,
        'len': 3,
        'default_methodid': 'ZX3',
        'trend': '/trend?lotteryid=shssl&count=30',
        'desc': '05:00-21:30 每30分钟一期，全天23期',
        modes
    },
    jskl3: {
        'dyprize': true,
        'name': '江苏快三',
        'pattern': 'ks',
        'type': 4,
        'len': 3,
        'default_methodid': 'KSHZ',
        'trend': '/trend?lotteryid=jskl3&count=30',
        'desc': '08:37-22:07每10分钟一期，全天82期',
        modes
    },
    ahkl3: {
        'dyprize': true,
        'name': '江苏快三',
        'pattern': 'ks',
        'type': 4,
        'len': 3,
        'default_methodid': 'KSHZ',
        'trend': '/trend?lotteryid=ahkl3&count=30',
        'desc': '08:37-22:07每10分钟一期，全天82期',
        modes
    },
    p3p5: {
        'dyprize': true,
        'name': '排列三、五',
        'pattern': 'p3p5',
        'type': 5,
        'len': 5,
        'default_methodid': 'QZX3',
        'trend': '/trend?lotteryid=p3p5&count=30',
        'desc': '当天20:30-第二天20:00，每天一期',
        modes
    },
    pk10: {
        'dyprize': true,
        'name': '北京PK拾',
        'pattern': 'pk10',
        'type': 3,
        'len': 10,
        'default_methodid': 'QZX1',
        'trend': '/trend?lotteryid=pk10&count=30',
        'desc': '当天9:00-24:00，每天179期',
        modes
    },
    dfpk10: {
        'dyprize': true,
        'name': '斗牛PK拾',
        'pattern': 'pk10',
        'type': 3,
        'len': 10,
        'default_methodid': 'QZX1',
        'trend': '/trend?lotteryid=dfpk10&count=30',
        'desc': '当天9:00-24:00，每天179期',
        modes
    }
};
